#!/bin/bash

# Checking to see if Joomla already exists. If it does then won't copy from /usr/src/ otherwise we will.

if [[ $(find /var/www/$DOCUMENT_ROOT -mindepth 1 ! -name index.html -a ! -name index.nginx-debian.html -a ! -name phpinfo.php -print -quit | wc -l) -ne 0 ]]; then
    echo "Users document root directory not empty. Not touching content."
    exit 0
fi

set -e

echo >&2 "Joomla not found in /var/www/html - copying now..."

rm -f /var/www/html/index.html
rm -f /var/www/html/index.nginx-debian.html
rm -f /var/www/html/phpinfo.php

tar -x -z -f /usr/src/joomla.tar.gz -C /var/www/html/

echo >&2 "Complete! Joomla has been successfully copied to /var/www/html/"

# php /makedb.php "$JOOMLA_DB_HOST" "$JOOMLA_DB_USER" "$JOOMLA_DB_PASSWORD" "$JOOMLA_DB_NAME"
